// <auto-generated />
using System;
using ECommerceApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241121210243_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceApi.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "lanches1.png",
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "combos1.png",
                            Name = "Combos"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "naturais1.png",
                            Name = "Naturals"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "refrigerantes1.png",
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "sucos1.png",
                            Name = "Juices"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "sobremesas1.png",
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("ECommerceApi.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerceApi.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Popular")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            BestSeller = true,
                            CategoryId = 1,
                            Details = "Plain bread, seasoned beef hamburger, onion, mustard and ketchup.",
                            ImageUrl = "hamburger1.jpeg",
                            InStock = 13,
                            Name = "Hamburger",
                            Popular = true,
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 1,
                            Details = "Plain bread, seasoned beef hamburger and cheese overall.",
                            ImageUrl = "hamburger3.jpeg",
                            InStock = 10,
                            Name = "CheeseBurger",
                            Popular = true,
                            Price = 18m
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 1,
                            Details = "Plain bread, seasoned beef hamburger, onion, lettuce, mustard and ketchup.",
                            ImageUrl = "hamburger4.jpeg",
                            InStock = 13,
                            Name = "CheeseSalad",
                            Popular = false,
                            Price = 19m
                        },
                        new
                        {
                            Id = 4,
                            Available = false,
                            BestSeller = false,
                            CategoryId = 2,
                            Details = "Plain bread, seasoned beef hamburger, cheese, french fries and soda.",
                            ImageUrl = "combo1.jpeg",
                            InStock = 10,
                            Name = "Hamburger, french fries, soda",
                            Popular = true,
                            Price = 25m
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 2,
                            Details = "Plain bread, beef hamburger, onion, mayonnaise, ketchup, french fries and soda.",
                            ImageUrl = "combo2.jpeg",
                            InStock = 13,
                            Name = "CheeseBurger, french fries, soda",
                            Popular = false,
                            Price = 27m
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 2,
                            Details = "Plain bread, beef hamburger, onion, mayonnaise, ketchup, french fries and soda.",
                            ImageUrl = "combo3.jpeg",
                            InStock = 10,
                            Name = "CheeseSalad, french fries, soda",
                            Popular = true,
                            Price = 28m
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 3,
                            Details = "Whole-corn bread with leaves and tomato.",
                            ImageUrl = "lanche_natural1.jpeg",
                            InStock = 13,
                            Name = "Natural snack with leaves",
                            Popular = false,
                            Price = 14m
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 3,
                            Details = "Whole-corn bread, leaves, tomato and cheese.",
                            ImageUrl = "lanche_natural2.jpeg",
                            InStock = 10,
                            Name = "Natural snack with cheese",
                            Popular = true,
                            Price = 15m
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 3,
                            Details = "Vegan snack with healthy ingredients.",
                            ImageUrl = "lanche_vegano1.jpeg",
                            InStock = 18,
                            Name = "Vegan snack",
                            Popular = false,
                            Price = 25m
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Coca Cola",
                            ImageUrl = "coca_cola1.jpeg",
                            InStock = 7,
                            Name = "Coca-Cola",
                            Popular = true,
                            Price = 21m
                        },
                        new
                        {
                            Id = 11,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Guaraná",
                            ImageUrl = "guarana1.jpeg",
                            InStock = 6,
                            Name = "Guaraná",
                            Popular = false,
                            Price = 25m
                        },
                        new
                        {
                            Id = 12,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Pepsi",
                            ImageUrl = "pepsi1.jpeg",
                            InStock = 6,
                            Name = "Pepsi",
                            Popular = false,
                            Price = 21m
                        },
                        new
                        {
                            Id = 13,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 5,
                            Details = "Nutritious and tasty orange juice.",
                            ImageUrl = "suco_laranja.jpeg",
                            InStock = 10,
                            Name = "Orange juice",
                            Popular = false,
                            Price = 11m
                        },
                        new
                        {
                            Id = 14,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 5,
                            Details = "Fresh strawberries juice.",
                            ImageUrl = "suco_morango1.jpeg",
                            InStock = 13,
                            Name = "Strawberry juice",
                            Popular = false,
                            Price = 15m
                        },
                        new
                        {
                            Id = 15,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 5,
                            Details = "Natural and sugarless grape juice.",
                            ImageUrl = "suco_uva1.jpeg",
                            InStock = 10,
                            Name = "Grape juice",
                            Popular = false,
                            Price = 13m
                        },
                        new
                        {
                            Id = 16,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 4,
                            Details = "Fresh mineral water.",
                            ImageUrl = "agua_mineral1.jpeg",
                            InStock = 10,
                            Name = "Water",
                            Popular = false,
                            Price = 5m
                        },
                        new
                        {
                            Id = 17,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 6,
                            Details = "Chocolate cookies with chocolate chips.",
                            ImageUrl = "cookie1.jpeg",
                            InStock = 10,
                            Name = "Chocolate cookies",
                            Popular = true,
                            Price = 8m
                        },
                        new
                        {
                            Id = 18,
                            Available = true,
                            BestSeller = true,
                            CategoryId = 6,
                            Details = "Crunchy and tasty vanilla cookies.",
                            ImageUrl = "cookie2.jpeg",
                            InStock = 13,
                            Name = "Vanilla cookies",
                            Popular = false,
                            Price = 8m
                        },
                        new
                        {
                            Id = 19,
                            Available = true,
                            BestSeller = false,
                            CategoryId = 6,
                            Details = "Swiss tort with filling.",
                            ImageUrl = "torta_suica1.jpeg",
                            InStock = 10,
                            Name = "Swiss tort",
                            Popular = true,
                            Price = 10m
                        });
                });

            modelBuilder.Entity("ECommerceApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommerceApi.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Product", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApi.Entities.Order", b =>
                {
                    b.HasOne("ECommerceApi.Entities.User", null)
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApi.Entities.OrderDetail", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Product", b =>
                {
                    b.HasOne("ECommerceApi.Entities.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceApi.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ECommerceApi.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ECommerceApi.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
